[package]
name = "loam-sdk-ft"
version = "0.6.4"
edition = "2021"
description = "A Riff for a fungible token"
license = "Apache-2.0"
repository = "https://github.com/willemneal/loam-sdk"

[dependencies]
loam-sdk = { path = "../loam-sdk", version = "0.6.3", features = [
    "loam-soroban-sdk",
] }

[package.metadata.loam]
riff = true
