[package]
name = "loam-soroban-sdk"
version = "0.6.4"
edition = "2021"
description = "A wrapper around the soroban-sdk, providing some soroban specific traits"
license = "Apache-2.0"
repository = "https://github.com/willemneal/loam-sdk"

[lib]
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loam-sdk-macro = { path = "../loam-sdk-macro", version = "0.6.4" }

[dependencies.soroban-sdk]
version = "0.9.2"
features = ["alloc"]



[features]
default = []
testutils = ["soroban-sdk/testutils"]
